### ISSUE TITLE
Setup-cog step failed when install cuda

### ISSUE THREAD

**Issue by alt1o** [replicate/setup-cog#26]
Have the same issues with #14 

I'm using GitHub's default runners: ubuntu-latest

<img width="1055" alt="image" src="https://github.com/replicate/setup-cog/assets/21084335/36969a16-0fdd-4f23-9c27-c6d10716bc48">

**Comment by TediPapajorgji** [comment]
happening here as well!

**Comment by zeke** [comment]
Hey folks. 👋🏼 

If you don't specifically need CUDA, you can bypass installing CUDA in your workflow by setting `install-cuda` to false. See https://github.com/replicate/setup-cog?tab=readme-ov-file#inputs

Cog can actually build and push most models without a GPU environment, and without CUDA, so I’d recommend giving that a try.

I just cut a new release of the setup-cog action with a bumped version of the cuda-toolkit installer.

If disabling install-cuda doesn’t work for you, please try using `replicate/setup-cog@v1.0.4` in your workflow and let us know if that resolves the issue.

https://github.com/replicate/setup-cog/releases/tag/v1.0.4

**Comment by zeke** [comment]
This should be fixed in newer versions. Closing this issue, but please give a shout if you're still seeing issues.
