### ISSUE TITLE
Wild idea: Default to NOT installing CUDA

### ISSUE THREAD

**Issue by zeke** [replicate/setup-cog#31]
This Action has an [`install-cuda`](https://github.com/replicate/setup-cog/blob/1d47a7caf7e6dcd59550277de189e62c60b67469/README.md#install-cuda) input that defaults to `true`.

But in most cases, you don't need CUDA to build and push a model.

Also CUDA installations often fail.

Even when they don't fail, the CUDA installation slows this action down significantly.

WIld idea: Cut a new major version (v2) of this Action that switches the default value of this input from `true` to `false`.

cc @anotherjesse @mattt

**Comment by mattt** [comment]
That sounds reasonable to me. I support this plan.
