### ISSUE TITLE
Add v1 tag or fix code example in README

### ISSUE THREAD

**Issue by marckohlbrugge** [replicate/setup-cog#6]
The readme has the following code example:

https://github.com/replicate/setup-cog/blob/e262c379f753ca7c0ef27be69708cb5ad71ddb84/README.md?plain=1#L56

However, there's no `v1` tag in the repo, so the above code will not work:

```
Error: Unable to resolve action `replicate/setup-cog@v1`, unable to find version `v1`
```

There's two possible solutions:

1. Update the code example to link to the latest tag (`v1.0.2` at the time of writing)
2. Add `v1` tag that always links to the latest `v1.x` commit (preferred)

I believe there are some GitHub Actions available this repo could use, to automatically keep an updated `v1` tag

**Comment by zeke** [comment]
Ah thanks for reporting @marckohlbrugge

I mistakenly thought that GitHub Actions did some kind of SemVer range resolution on patterns like `v1`, automatically installing the latest major version that matches. Like `1.x`.

But it doesn't work that way! TIL. Whoops.

So I guess we need to update the release process to create a sibling tag that bumps that `v{major}` every time?

**Comment by zeke** [comment]
I've created a [new `v1` tag](https://github.com/replicate/setup-cog/tags) and opened a PR to document the release process, so feature releases will always have that fuzzy major-version identifier: https://github.com/replicate/setup-cog/pull/15

**Comment by marckohlbrugge** [comment]
> So I guess we need to update the release process to create a sibling tag that bumps that `v{major}` every time?

Yes, I believe so. You can automate this with a GitHub Action. I've never done this, but a Google search turned up this example: https://gist.github.com/cicirello/ade1d559a89104140557389365154bc1
