### ISSUE TITLE
CPU only version?

### ISSUE THREAD

**Issue by luismavs** [replicate/setup-cog#9]
Hi,

The step:

      - name: Install NVIDIA CUDA Toolkit
        uses: Jimver/cuda-toolkit@6974ecc945579a89135a1e1d9eac96ec361a1171 # v0.2.10

Is not needed for CPU-only containers, would it be possible to add some kind of flag to sidestep this?

Thanks!

**Comment by zeke** [comment]
Yep, good call. 👍🏼

**Comment by zeke** [comment]
Feel free to open a PR for this if I don't get to it first.

**Comment by zeke** [comment]
Resolved by https://github.com/replicate/setup-cog/pull/13 !
